- Elias_Jonsson.html
> adds html structure to Elias_jonsson.html

- Elias_Jonsson.html
> adds title to Elias_Jonsson.html

- Diler_Ciftci.html
> Filled Header

- Elias_Jonsson.html
> adds paragraph for Elias

- Elias_Jonsson.html
adds hometown info to Elias 
closes #32
> adds-hometown-info-Elias

- Diler_Ciftci.html
> Added Hometown to paragraph

- Diler_Ciftci.html
> Adds h1 to header

- Elias_Jonsson.html
> adds navbar for Elias_Jonsson.html

- Diler_Ciftci.html
> Adds link to navbar Diler_Ciftci.html

- Danilo_Bardalez.html
> back_to_index_Danilo_Bardalez.html

- Diler_Ciftci.html
> adds 4 things Im good at Diler_Ciftci.html

- Elias_Jonsson.html
> adds class to header for Elias_Jonsson.html

- Elias_Jonsson.html
> adds class to nav Elias

- Danilo_Bardalez.html
- Diler_Ciftci.html
> adds class for header

- Danilo_Bardalez.html
> add_four_things_Danilo_Bardalez.html

- Diler_Ciftci.html
> Removed Paragraph Diler_Ciftci.html

- Diler_Ciftci.html
> Added h3 Diler_Ciftci.html

- style.css
> updated textdecoration in navbar

- Diler_Ciftci.html
> add class to img Diler.Ciftci.html

- Danilo_Bardalez.html
> add_picture_Danilo_bardalez.html

- style.css
> adds style for profilepictures

- Danilo_Bardalez.html
> add_h3_Danilo_Bardalez.html

- style.css
> adds margin left and right for profileimg

- style.css
> removes p from style.css

- style.css
> centered text below picture
